### ISSUE TITLE
[Error] existing rtl_fm instance running, I quit

### ISSUE THREAD

**Issue by surfrod** [reynico/raspberry-noaa#46]
**Describe the bug**
Per my previous problems with Meteor files and processing running out of space, I upgraded to a 64gig sd card.
Now I see a meteor audio file and am still searching through mail to see what happened creating the image, when
I ran across this error "ERROR : There is an existing rtl_fm instance running, I quit"

Any thoughts as to what happened, why this happened and how to get more debugging info out?

**Comment by reynico** [comment]
Hi!
Time ago I introduced a condition inside receive_meteor.sh that kills any rtl_fm process to prefer the meteor passes instead of the NOAA ones.

> "ERROR : There is an existing rtl_fm instance running, I quit"

This error belongs just to receive.sh (NOAA reception) that exits the receive.sh script during a current reception (I.e. when satellite footprints are overlapping)

**Comment by surfrod** [comment]
ok, so it's not an issue, just an obfuscated debug message 👍 

Thanks
