### ISSUE TITLE
Scheduler not generating passes.

### ISSUE THREAD

**Issue by Anjum9694** [reynico/raspberry-noaa#84]
Hi I installed using the installer script and rebooted the Pi. The cornjob doesn't seem to be working so I ran the bash command verbose, don't see any errors but I ran atq afterwards there doesn't seem to be any passes. The webserver works fine but it doesn't show any passes either.

![dadas](https://user-images.githubusercontent.com/31078090/102810183-11321a00-43e5-11eb-93dc-32368c5314c3.JPG)

**Comment by reynico** [comment]
Hi!
Most likely that's because there isn't any new pass for this day. Judging by your Github profile you're located in Maldives (GMT +5) so it's almost midnight. The cronjob will run automatically in a few minutes (00:01)!

just to be sure, please also check that your Raspberry PI date, time and timezone settings are correct

**Comment by Anjum9694** [comment]
LOL yeah. Glad there's no issue with my installation then.
![dasdaa](https://user-images.githubusercontent.com/31078090/102812733-59533b80-43e9-11eb-9e22-a89797dd14fe.JPG)
